--stngs.lua - default settings

-- This file is under copyright, and is bound to the agreement stated in the EULA.
-- Any 3rd party content has been used as either public domain or with permission.
-- © Copyright 2016-2017 Aritz Beobide-Cardinal All rights reserved.
ARCPhone.Loaded = false
ARCPhone.SpecialSettings = {}
ARCPhone.SpecialSettings.EmergencyNumbers = {}
ARCPhone.SpecialSettings.EmergencyNumbers["911"] = {"TEAM_POLICE","TEAM_MAYOR"}
ARCPhone.EmergencyNumbers = {}
ARCPhone.EmergencyNumbers["911"] = true

ARCPhone.Settings = {}

--[[
 ____   ___    _   _  ___ _____   _____ ____ ___ _____   _____ _   _ _____   _    _   _   _      _____ ___ _     _____ _ 
|  _ \ / _ \  | \ | |/ _ \_   _| | ____|  _ \_ _|_   _| |_   _| | | | ____| | |  | | | | / \    |  ___|_ _| |   | ____| |
| | | | | | | |  \| | | | || |   |  _| | | | | |  | |     | | | |_| |  _|   | |  | | | |/ _ \   | |_   | || |   |  _| | |
| |_| | |_| | | |\  | |_| || |   | |___| |_| | |  | |     | | |  _  | |___  | |__| |_| / ___ \  |  _|  | || |___| |___|_|
|____/ \___/  |_| \_|\___/ |_|   |_____|____/___| |_|     |_| |_| |_|_____| |_____\___/_/   \_\ |_|   |___|_____|_____(_)

 ____   ___    _   _  ___ _____   _____ ____ ___ _____   _____ _   _ _____   _    _   _   _      _____ ___ _     _____ _ 
|  _ \ / _ \  | \ | |/ _ \_   _| | ____|  _ \_ _|_   _| |_   _| | | | ____| | |  | | | | / \    |  ___|_ _| |   | ____| |
| | | | | | | |  \| | | | || |   |  _| | | | | |  | |     | | | |_| |  _|   | |  | | | |/ _ \   | |_   | || |   |  _| | |
| |_| | |_| | | |\  | |_| || |   | |___| |_| | |  | |     | | |  _  | |___  | |__| |_| / ___ \  |  _|  | || |___| |___|_|
|____/ \___/  |_| \_|\___/ |_|   |_____|____/___| |_|     |_| |_| |_|_____| |_____\___/_/   \_\ |_|   |___|_____|_____(_)
                                                                                                                         

 ____   ___    _   _  ___ _____   _____ ____ ___ _____   _____ _   _ _____   _    _   _   _      _____ ___ _     _____ _ 
|  _ \ / _ \  | \ | |/ _ \_   _| | ____|  _ \_ _|_   _| |_   _| | | | ____| | |  | | | | / \    |  ___|_ _| |   | ____| |
| | | | | | | |  \| | | | || |   |  _| | | | | |  | |     | | | |_| |  _|   | |  | | | |/ _ \   | |_   | || |   |  _| | |
| |_| | |_| | | |\  | |_| || |   | |___| |_| | |  | |     | | |  _  | |___  | |__| |_| / ___ \  |  _|  | || |___| |___|_|
|____/ \___/  |_| \_|\___/ |_|   |_____|____/___| |_|     |_| |_| |_|_____| |_____\___/_/   \_\ |_|   |___|_____|_____(_)
                                                                                                                         
Let me try to explain something to you...
																														 
DO NOT EDIT THIS FILE TO CHANGE THE CONFIG! READ THE README!
These are the default settings in order to prevent you from screwing it up!

arcphone help
^ GIVES YOU A FULL AND DETAILED DESCRIPTION OF ALL COMMANDS

arcphone settings_help (setting)
^ GIVES YOU A FULL DESCRIPTION OF ALL SETTINGS (Leave blank to show a list of all settings.)

arcphone settings (setting) (value)
^ SETS THE SETTING YOU WANT TO THE SPECIFIED VALUE.
]]
function ARCPhone.SettingsReset() --DO NOT EDIT THIS!!!!
	ARCPhone.Settings["admins"] = {"owner","superadmin","admin"} 
	ARCPhone.Settings["name"] = "ARCPhone" --DO NOT EDIT THIS!!!!
	ARCPhone.Settings["name_long"] = "ARitz Cracker Phone" --DO NOT EDIT THIS!!!!
	ARCPhone.Settings["antenna_range"] = 5000 --DO NOT EDIT THIS!!!!
	ARCPhone.Settings["antenna_strength"] = 1435 --DO NOT EDIT THIS!!!!
	ARCPhone.Settings["jammer_range"] = 500 --DO NOT EDIT THIS!!!!
	ARCPhone.Settings["jammer_strength"] = 75 --DO NOT EDIT THIS!!!!
	ARCPhone.Settings["max_lines"] = 20
	ARCPhone.Settings["realistic_reception"] = true
	ARCPhone.Settings["atmos_support"] = false
end
--
ARCPhone.SettingsReset()